application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /_static
  static_dir: static

- url: /_api/.*
  script: _go_app
  
- url: /.*
  static_files: index.html
  upload: index.html