application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /_vendor/jquery.js
  static_files: bower_components/jquery/dist/jquery.js
  upload: bower_components/jquery/dist/jquery.js

- url: /_vendor/bootstrap.js
  static_files: bower_components/bootstrap/dist/js/bootstrap.js
  upload: bower_components/bootstrap/dist/js/bootstrap.js

- url: /_vendor/css/bootstrap.css
  static_files: bower_components/bootstrap/dist/css/bootstrap.min.css
  upload: bower_components/bootstrap/dist/css/bootstrap.min.css

- url: /_vendor/fonts/(.*)
  static_files: bower_components/bootstrap/dist/fonts/\1
  upload: bower_components/bootstrap/dist/fonts/.*

- url: /_vendor/bootstrap.css
  static_files: bower_components/bootstrap/dist/css/bootstrap.min.css
  upload: bower_components/bootstrap/dist/js/bootstrap.js

- url: /_vendor/angular.js
  static_files: bower_components/angular/angular.js
  upload: bower_components/angular/angular.js

- url: /_vendor/angular-resource.js
  static_files: bower_components/angular-resource/angular-resource.js
  upload: bower_components/angular-resource/angular-resource.js

- url: /_vendor/angular-route.js
  static_files: bower_components/angular-route/angular-route.js
  upload: bower_components/angular-route/angular-route.js

- url: /_vendor/bootstrap3-typeahead.js
  static_files: bower_components/bootstrap3-typeahead/bootstrap3-typeahead.js
  upload: bower_components/bootstrap3-typeahead/bootstrap3-typeahead.js

- url: /_static
  static_dir: static

- url: /_api/.*
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index.html